title: Outrageous
author: Hangsia
email: honghangsia@koompi.org
description: > # this means to ignore newlines until "baseurl:"
        Too fast to live, Too young to die

# social links
twitter_username: hangsiahong # DO NOT include the @ character, or else the build will fail!
github_username:  hangsiahong # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
